name: AI PR via comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-pr-using-aipr:
    # Fire only when the trigger comment phrase is present
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, 'Create PR with AIPR 🚀')
    runs-on: ubuntu-latest
    steps:
      - name: Executing AIPR action
        uses: alexanmtz/AIPR@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_tokens: 200        # optional; default 200
          target_branch: main       # change if your default branch is different
          file_chunks: 10000        # optional; chunk size
